name: "JaCoCo line covered ratio (from the pom.xml)"

on:
  push:
    branches: [ "main","develop" ]
  pull_request:
    branches: [ "main","develop" ]

permissions: # added using https://github.com/step-security/secure-repo
  checks: write
  contents: read

jobs:
  jacoco_coverage_report:
    name: JaCoCo coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'liberica'
          java-version: '25'
          check-latest: true
          cache: 'maven'

      - name: Verify Java Installation
        run: java -version

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Test
        run: |
          ./mvnw -B clean test \
          -Djava.awt.headless=false \
          -Dsun.awt.disablegrab=true \
          -Duser.language=fr -Duser.country=FR \
          -f pom.xml

      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@4fc6bf270fe893e8dda5467e432253a6961345b8 # v5.0
        with:
          coverage_results_path: target/site/jacoco/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 70
          fail_below_threshold: true
          publish_only_summary: false

      - name: Add JaCoCo report to workflow run summary
        run: |
          echo "| Outcome | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | ---: |" >> $GITHUB_STEP_SUMMARY
          echo "| Code Coverage % | **${{ steps.jacoco_reporter.outputs.coverage_percentage }}** |" >> $GITHUB_STEP_SUMMARY
          echo "| :heavy_check_mark: Number of Lines Covered | ${{ steps.jacoco_reporter.outputs.covered_lines }} |" >> $GITHUB_STEP_SUMMARY
          echo "| :x: Number of Lines Missed | ${{ steps.jacoco_reporter.outputs.missed_lines }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Total Number of Lines | ${{ steps.jacoco_reporter.outputs.total_lines }} |" >> $GITHUB_STEP_SUMMARY
